# Generated by Django 4.2.30 on 2026-08-20 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grievances', '0015_grievance_spam_reviewed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_grievance_limit', models.PositiveSmallIntegerField(default=3, help_text='Maximum number of grievances a user can submit per calendar day.')),
                ('escalation_hours', models.FloatField(default=168.0, help_text='Hours of inactivity before a grievance is auto-escalated (e.g. 168 = 7 days).')),
                ('escalation_interval_min', models.FloatField(default=60.0, help_text='How often (in minutes) the escalation checker runs.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Campus Admin who last modified these settings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
